version: '3.3'

services:
  postgres:
    image: postgres:alpine
    restart: on-failure
    environment:
      - POSTGRES_DB=passwall
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    volumes:
      - $HOME/docker/volumes/passwall-postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
  
  passwall-server:
    container_name: passwall-server
    image: passwall/passwall-server:latest
    restart: always
    environment:
      - PW_DB_NAME=passwall
      - PW_DB_USERNAME=postgres
      - PW_DB_PASSWORD=password
      - PW_DB_HOST=postgres
      - PW_DB_PORT=5432
      - PW_DB_LOG_MODE=false
      - PW_DB_SSL_MODE=disable
    build:
      context: .
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 3625:3625
    volumes:
      - $HOME/docker/volumes/passwall-server:/app/config
  nginx:
    image: umputun/nginx-le:v1.4.2
    hostname: nginx
    restart: always
    container_name: nginx
    volumes:
      - ./etc/ssl:/etc/nginx/ssl
      - ./etc/service.conf:/etc/nginx/service.conf
    ports:
      - "80:80"
      - "443:443"
    environment:
      - TZ=UTC
      - LETSENCRYPT=true
      - LE_EMAIL=email@yourdomain.com
      - LE_FQDN=yourdomain.com